// =============================================
// TacticAI — Football Tactical Data
// AI-Generated Analysis of 4-2-3-1 & 5-3-2
// =============================================

const SYSTEMS = {
  "4231": {
    name: "4-2-3-1",
    nickname: "El Sistema Universal",
    icon: "⚡",
    description: `El sistema 4-2-3-1 es la formación más utilizada en el fútbol moderno de alto nivel. Es reconocible por su estructura defensiva sólida de cuatro, la plataforma pivote de doble mediocampista, una línea ofensiva creativa de tres detrás del delantero centro. Esta formación permite controlar el mediocampo con equilibrio entre ataque y defensa, es versátil ante distintos rivales y facilita las transiciones rápidas.`,
    badges: [
      { label: "Alta Posesión", type: "control" },
      { label: "Pressing Intenso", type: "pressing" },
      { label: "Ataque Versátil", type: "attack" },
      { label: "Bloque Defensivo", type: "defense" },
    ],
    strengths: [
      "Dominio del mediocampo mediante el doble pivote: filtra pases de balón largo, recupera segunda jugada y protege la línea defensiva.",
      "Gran versatilidad táctica: puede transformarse en un 4-4-2 defensivo o en un 4-3-3 ofensivo según el momento del partido.",
      "El mediapunta actúa como nexo entre líneas, siendo casi imposible de marcar por los sistemas de medios oponentes.",
      "Los extremos generan amplitud y profundidad, forzando al rival a abrir su bloque y creando espacios para la incursión del '10'.",
      "Facilita el pressing alto de manera coordinada: el '9' presiona al portero rival, los extremos bloquean los carrileros y el mediapunta ejerce presión sobre el mediocentro rival.",
      "Ideal para equipos con un 9 de área puro y un mediapunta muy técnico, maximizando sus cualidades naturales.",
      "Las transiciones ofensivas son rápidas: recuperado el balón en el mediocampo, hay tres líneas de pase verticales abiertas de inmediato.",
    ],
    weaknesses: [
      "Si el rival supera el doble pivote con velocidad, la defensa queda expuesta de forma directa, sin coberturas intermedias.",
      "La amplitud depende casi exclusivamente de los laterales, que deben subir constantemente, lo que genera riesgos a la espalda en las bandas.",
      "El delantero centro puede quedar aislado si los tres mediapuntas son pasivos o si el mediapunta no conecta con él.",
      "Contra sistemas de 5 defensas la defensa puede saturarse en el centro, anulando al mediapunta y limitando las combinaciones.",
      "Alta dependencia de la calidad individual: sin un mediapunta top, el sistema pierde su eje creativo y la conexión entre líneas.",
      "Exige una alta intensidad física del doble pivote; si uno se fatiga, el sistema queda descompensado y el mediocampo sufre.",
    ],
    positions: [
      {
        id: "gk",
        name: "Portero",
        abbr: "PO",
        type: "gk",
        shortRole: "Portero moderno: inicio de juego y organización defensiva.",
        role: `El portero en el 4-2-3-1 moderno es el "primer jugador de campo". Su misión va más allá de parar tiros: participa activamente en la construcción desde atrás, siendo la primera opción de pase bajo presión. Debe leer el juego para anticipar balones largos del rival, salir de la zona para cortar el juego en profundidad y comunicar constantemente la posición de sus defensas.`,
        attrs: [
          { label: "Juego con los pies", type: "technical" },
          { label: "Liderazgo", type: "mental" },
          { label: "Reflejos", type: "physical" },
          { label: "Salidas", type: "tactical" },
        ],
        tasks: [
          "Inicio del juego: pase corto a los centrales bajo presión rival.",
          "Organizar la línea defensiva con indicaciones verbales constantes.",
          "Salir a cortar balones en profundidad jugados por el rival.",
          "Cubrir el espacio a la espalda cuando los laterales se proyectan al ataque.",
        ],
      },
      {
        id: "lb",
        name: "Lateral Izquierdo",
        abbr: "LI",
        type: "def",
        shortRole: "Carrilero dinámico: amplitud y profundidad en ataque.",
        role: `El lateral izquierdo en el 4-2-3-1 es un jugador de doble función: debe ser un defensor solido en fase sin balón y un carrilero ofensivo en fase de ataque. Sube por su banda, demostrando superioridad ante el extremo rival para crear situaciones de 2v1, centrando desde línea de fondo o recortando. En defensa, cierra la banda y comunica constantemente con el central izquierdo para no dejar espacio a la espalda.`,
        attrs: [
          { label: "Resistencia", type: "physical" },
          { label: "Centros", type: "technical" },
          { label: "Posicionamiento", type: "tactical" },
          { label: "1vs1", type: "technical" },
        ],
        tasks: [
          "Proyectarse hacia el ataque por la banda izquierda como alternativa de amplitud.",
          "Recibir y distribuir rápidamente, generando superioridades numéricas.",
          "Defender en 1v1 al extremo/carrilero rival y cerrar la banda en transición.",
          "Coordinarse con el central izquierdo para no dejar espacios a la espalda.",
        ],
      },
      {
        id: "lcb",
        name: "Central Izquierdo",
        abbr: "DCI",
        type: "def",
        shortRole: "Defensa sólido con capacidad de inicio de juego.",
        role: `El central izquierdo ancla la estructura defensiva. Junto a su compañero, establece una línea de cuatro compacta y organizada. Debe anticipar, ganar duelos aéreos y leer el juego para interceptar. En la fase de construcción, recibe del portero y distribuye hacia el lateral o el doble pivote. La comunicación constante con el lateral y el central derecho es clave para mantener la línea bien organizada.`,
        attrs: [
          { label: "Anticipación", type: "mental" },
          { label: "Juego aéreo", type: "physical" },
          { label: "Pase largo", type: "technical" },
          { label: "Liderazgo", type: "mental" },
        ],
        tasks: [
          "Organizar la línea defensiva y gestionar la distancia inter-líneas.",
          "Ganar los duelos aéreos defensivos y las segundas jugadas.",
          "Iniciar el juego con pases limpios al pivote o al lateral.",
          "Zona de cobertura: cubrir al lateral cuando este sube al ataque.",
        ],
      },
      {
        id: "rcb",
        name: "Central Derecho",
        abbr: "DCD",
        type: "def",
        shortRole: "Líder defensivo, corta y anticipa con autoridad.",
        role: `El central derecho es generalmente el líder defensivo de referencia. Es quien da las instrucciones al bloque defensivo, marca al delantero rival en los duelos directos y filtra los balones verticales. En el 4-2-3-1 actual, es fundamental que también sea hábil con el balón en los pies, para facilitar la salida de balón bajo presión sin recurrir exclusivamente al balón largo.`,
        attrs: [
          { label: "Liderazgo vocal", type: "mental" },
          { label: "Anticipo", type: "tactical" },
          { label: "Construcción", type: "technical" },
          { label: "Duelos directos", type: "physical" },
        ],
        tasks: [
          "Dirigir al bloque defensivo en la organización sin balón.",
          "Marcar al 9 rival y ganar los duelos aéreos en el área propia.",
          "Conectar el juego con los pivotes mediante pases limpios y certeros.",
          "Coberturas al lateral derecho cuando este sube al ataque.",
        ],
      },
      {
        id: "rb",
        name: "Lateral Derecho",
        abbr: "LD",
        type: "def",
        shortRole: "Carrilero que genera superioridad y desdibla la banda.",
        role: `Espejo del lateral izquierdo, aporta profundidad por la derecha. En muchos sistemas modernos de 4-2-3-1 se le pide que actúe como un interior cuando el extremo se cierra, generando superioridades en la zona central a la derecha. En defensa, neutraliza al extremo rival y protege el carril. Es imprescindible su conexión con el extremo derecho para crear combinaciones fluidas.`,
        attrs: [
          { label: "Velocidad", type: "physical" },
          { label: "Proyección", type: "tactical" },
          { label: "Dribbling", type: "technical" },
          { label: "Regreso defensivo", type: "tactical" },
        ],
        tasks: [
          "Doblar al extremo derecho para generar superioridades (2v1) por banda.",
          "Dar amplitud o profundidad según la posición del extremo.",
          "Neutralizar en 1v1 al extremo rival en fase defensiva.",
          "Colaborar con el pivote más cercano para cerrar transiciones rivales.",
        ],
      },
      {
        id: "ldm1",
        name: "Pivote / Mediocentro Defensivo 1",
        abbr: "MCD1",
        type: "mid",
        shortRole: "Escudo defensivo y distribuidor desde la base.",
        role: `El primer pivote es el 'filtro' del mediocampo: intercepta, lucha, recupera y distribuye. Es el jugador que da equilibrio al sistema, posicionándose siempre para ofrecer el pase seguro cuando la construcción está en peligro. Su visión periférica y su capacidad para moverse entre líneas sin recibir presión directa son cualidades esenciales. Físicamente dominante, gana los duelos en la zona de más tráfico.`,
        attrs: [
          { label: "Pressing", type: "tactical" },
          { label: "Recuperación", type: "physical" },
          { label: "Visión de juego", type: "mental" },
          { label: "Pase corto", type: "technical" },
        ],
        tasks: [
          "Interceptar pases entre líneas del rival y recuperar el balón.",
          "Posicionarse como opción de pase segura entre la defensa y el mediocampo.",
          "Cubrir los espacios que deja la línea defensiva cuando avanza.",
          "Distribuir con criterio, priorizando la seguridad sobre la verticalidad.",
        ],
      },
      {
        id: "ldm2",
        name: "Pivote / Mediocentro Defensivo 2",
        abbr: "MCD2",
        type: "mid",
        shortRole: "Enlace y presencia física en el eje del campo.",
        role: `El segundo pivote complementa al primero con características ligeramente distintas: mientras uno puede ser más destructor, el otro suele ser más técnico y con mayor capacidad de pase largo. Juntos forman la 'muralla' del mediocampo. Este pivote tiene algo más de libertad para avanzar en fase de posesión, generando superioridad numérica en el centro y siendo el primer paso de la construcción hacia el mediapunta.`,
        attrs: [
          { label: "Pase largo", type: "technical" },
          { label: "Ritmo de juego", type: "mental" },
          { label: "Duelos físicos", type: "physical" },
          { label: "Cobertura de espacios", type: "tactical" },
        ],
        tasks: [
          "Actuar como enlace entre defensa y mediapunta/extremos.",
          "Avanzar levemente para generar superioridad en la zona central.",
          "Cerrar al mediapunta rival cuando este baja a recibir.",
          "Cubrir al compañero cuando este sube al pase largo o a presionar.",
        ],
      },
      {
        id: "lw",
        name: "Extremo Izquierdo",
        abbr: "EI",
        type: "att",
        shortRole: "Desborde, profundidad y amenaza constante por banda.",
        role: `El extremo izquierdo da amplitud y amenaza constante por su banda. En el fútbol moderno suele ser un jugador 'invertido': zurdo jugando por la derecha o diestro por la izquierda — en este caso puede encarar hacia dentro para disparar o combinar. Su trabajo defensivo es fundamental: cuando el rival tiene el balón, debe bajar para tapar la línea de pase al lateral rival y colaborar en el 4-4-2 defensivo.`,
        attrs: [
          { label: "Velocidad", type: "physical" },
          { label: "1vs1", type: "technical" },
          { label: "Centro/disparo", type: "technical" },
          { label: "Recorrido ofensivo/defensivo", type: "tactical" },
        ],
        tasks: [
          "Desbordar al lateral contrario en el juego directo y generar el 1v1.",
          "Centrar desde línea de fondo o combinar con el lateral subido.",
          "En fase defensiva: bajar hasta la línea del mediocentro para compactar el 4-4-2.",
          "Buscar el espacio entre líneas cuando el mediapunta se aleja del centro.",
        ],
      },
      {
        id: "am",
        name: "Mediapunta",
        abbr: "MP",
        type: "att",
        shortRole: "El '10': cerebro creativo entre líneas, nexo y gol.",
        role: `El mediapunta — o '10' — es el eje creativo del sistema. Actúa en el espacio entre los centrocampistas rivales y sus defensas centrales, una zona donde es muy difícil de marcar. Desde aquí distribuye, genera el desmarque del '9', crea el pase de gol y en ocasiones culmina jugadas en el área. Su inteligencia táctica y su calidad técnica son determinantes para el funcionamiento del sistema.`,
        attrs: [
          { label: "Visión de juego", type: "mental" },
          { label: "Pase filtrado", type: "technical" },
          { label: "Movimiento sin balón", type: "tactical" },
          { label: "Definición", type: "technical" },
        ],
        tasks: [
          "Posicionarse entre las líneas rival para recibir 'de espaldas' y girar.",
          "Crear el pase de gol al delantero o al extremo desmarcado.",
          "Presionar al mediocentro rival como primera línea de presión.",
          "Llegar al área para rematar en segunda jugada o desde fuera del área.",
        ],
      },
      {
        id: "rw",
        name: "Extremo Derecho",
        abbr: "ED",
        type: "att",
        shortRole: "Velocidad y desequilibrio por la banda derecha.",
        role: `El extremo derecho replica el papel del extremo izquierdo pero en la banda contraria. En función de las características del jugador, puede ser un clásico (que profundiza y centra) o un extremo invertido (que entra a pierna cambiada y busca el disparo a portería). Su conexión con el lateral derecho es fundamental para sobrecargar la banda y generar ventajas numéricas en zonas de finalización.`,
        attrs: [
          { label: "Velocidad explosiva", type: "physical" },
          { label: "Precisión de centro", type: "technical" },
          { label: "Desmarque", type: "tactical" },
          { label: "Trabajo defensivo", type: "tactical" },
        ],
        tasks: [
          "Generar profundidad por la banda derecha, estirando la defensa rival.",
          "Asociarse con el lateral derecho para generar el 2v1.",
          "Definir en el área chica, en corredor o en la media luna.",
          "Presionar y ayudar defensivamente al lateral derecho en el sector.",
        ],
      },
      {
        id: "st",
        name: "Delantero Centro",
        abbr: "DC",
        type: "att",
        shortRole: "Referencia en punta: finalización, hold-up y presión.",
        role: `El delantero centro es la referencia atacante, el jugador que finaliza las jugadas colectivas. En fase ofensiva se mueve para crear espacio a los extremos, actúa de 'pared' para profundizar a los mediapuntas y remata desde distintas posiciones. En fase de presión, es el primero en presionar al portero rival para forzar el balón largo. Su inteligencia de movimiento y su efectividad en el área son sus cualidades más valoradas.`,
        attrs: [
          { label: "Finalización", type: "technical" },
          { label: "Juego de espaldas", type: "technical" },
          { label: "Movimiento en el área", type: "tactical" },
          { label: "Pressing alto", type: "tactical" },
        ],
        tasks: [
          "Rematar con eficacia desde cualquier posición dentro y fuera del área.",
          "Retener el balón de espaldas para que los mediapuntas se incorporen.",
          "Presionar al portero rival para forzar el balón largo y errores.",
          "Hacer el movimiento adecuado para 'abrir' espacios a los extremos que recortan.",
        ],
      },
    ],
    ratings: { ataque: 82, defensa: 75, mediocampo: 90, pressing: 85, versatilidad: 92, complejidad: 70 },
    compData: {
      posesion: { label: "Posesión", value: "Alta — el doble pivote y el mediapunta permiten circular el balón con orden.", win: true },
      pressing: { label: "Pressing", value: "Muy alto — estructura ideal para el pressing organizado de 5 líneas.", win: true },
      defensa: { label: "Solidez Defensiva", value: "Media-Alta — sólida línea de 4, pero dependiente del doble pivote.", win: false },
      ataque: { label: "Potencia Ofensiva", value: "Alta — 4 jugadores en fase de ataque generan múltiples alternativas.", win: true },
      adaptacion: { label: "Adaptabilidad", value: "Muy alta — puede transformarse en 4-3-3 o 4-4-2 fácilmente.", win: true },
      transiciones: { label: "Transiciones", value: "Excelentes — los extremos y el mediapunta activan la contra con rapidez.", win: true },
    },
  },

  "532": {
    name: "5-3-2",
    nickname: "El Bloque Sólido",
    icon: "🛡️",
    description: `El sistema 5-3-2 (también llamado 3-5-2 en fase ofensiva) es una formación de gran solidez estructural que prioriza el orden defensivo con tres centrales, mientras que los carrileros proveen amplitud en ataque transformando la línea de 5 en una solución híbrida. El triple pivote en el mediocampo da cobertura y aporta un jugador más en construcción. Dos delanteros trabajan en pareja, combinando movilidad con efectividad.`,
    badges: [
      { label: "Solidez Defensiva", type: "defense" },
      { label: "Amplitud en Ataque", type: "attack" },
      { label: "Presión Zonal", type: "pressing" },
      { label: "Bloque Bajo", type: "control" },
    ],
    strengths: [
      "Los tres centrales crean una barrera difícil de penetrar: uno siempre puede dar cobertura mientras los otros dos marcan.",
      "Los carrileros ofrecen una doble función — amplitud ofensiva en ataque y vuelven a la línea de cinco en defensa — creando una formación muy difícil de romper.",
      "El mediocampo de tres cubre bien el espacio central, siendo muy difícil para el rival jugar entre líneas.",
      "La pareja de delanteros trabaja junta en pressing, creando canales y trampas para la salida de balón rival.",
      "Anula a equipos con extremos veloces, ya que los carrileros pueden compactar rápidamente el bloque al recuperar.",
      "Excelente en situaciones de balón parado: con cinco atrás y tres en el mediocampo, el sistema tiene numbers para cualquier set piece.",
    ],
    weaknesses: [
      "Si los carrileros son superados al subir al ataque, deja espacios amplios en las bandas que el rival puede explotar.",
      "El mediocampo de tres puro puede sufrir contra equipos que usen doble pivote + mediapunta, siendo superados en el centro.",
      "La pareja de delanteros puede quedar aislada si el mediocampo no genera superioridades al proyectarse hacia delante.",
      "Puede resultar un sistema excesivamente reactivo: si el rival tiene el balón, el 5-3-2 tiende a ceder la iniciativa.",
      "Dificultad para generar amplitud en ataque si los carrileros no tienen la condición física para subir y bajar durante 90 minutos.",
      "Contra equipos con amplitud de cuatro (4-4-2, 4-2-3-1), el carrilero puede estar en inferioridad 1v2 en su banda.",
    ],
    positions: [
      {
        id: "gk",
        name: "Portero",
        abbr: "PO",
        type: "gk",
        shortRole: "Guardameta organizador y soporte en la construcción.",
        role: `En el 5-3-2, el portero actúa como sexto defensor en fase de construcción. Con tres centrales delante, tiene múltiples opciones de pase corto, pero también debe ser capaz de ejecutar el pase largo justo cuando el equipo busca la salida directa. Su capacidad de mando y de organización de la línea de cinco en las situaciones defensivas estáticas (córners, faltas) es determinante.`,
        attrs: [
          { label: "Juego con los pies", type: "technical" },
          { label: "Mando vocal", type: "mental" },
          { label: "Pase largo", type: "technical" },
          { label: "Salidas a centros", type: "tactical" },
        ],
        tasks: [
          "Comunicar las posiciones a la línea de cinco.",
          "Ofrecer la línea de pase segura cuando la presión rival es alta.",
          "Ejecutar el pase largo preciso cuando la construcción no es viable.",
          "Salir a centros laterales con autoridad por su zona extensa de acción.",
        ],
      },
      {
        id: "lcb",
        name: "Central Izquierdo",
        abbr: "DCI",
        type: "def",
        shortRole: "Defensa lateral del trío: cobertura y salida por la izquierda.",
        role: `El central izquierdo en la línea de tres tiene funciones específicas: cubre al carrilero izquierdo cuando este sube, intercepta balones al espacio en la zona izquierda y se comunica constantemente con el carrilero para no dejar espacios descubiertos. También participa en la salida de balón, siendo una opción para el portero y distribuyendo hacia el carrilero con pases cortos y medios.`,
        attrs: [
          { label: "Cobriendo el espacio", type: "tactical" },
          { label: "Pase al carrilero", type: "technical" },
          { label: "Anticipo", type: "mental" },
          { label: "Juego aéreo", type: "physical" },
        ],
        tasks: [
          "Cubrir el espacio a la espalda del carrilero izquierdo cuando sube.",
          "Anticipar en la zona izquierda del área e interceptar balones al hueco de banda.",
          "Activar al carrilero izquierdo con pases precisos para la incorporación.",
          "Mantener la línea alta con el central pivote para salir al fuera de juego.",
        ],
      },
      {
        id: "cb",
        name: "Central Pivote",
        abbr: "DCP",
        type: "def",
        shortRole: "El líder del trío: organizador, referente defensivo.",
        role: `El central pivote es el corazón de la defensa de tres. Marca al delantero más peligroso del rival, dirige a los compañeros, sale a cortar el juego en profundidad y actúa como organizador de toda la línea. En fase de posesión, es el pivote de la construcción: recibe del portero y decide si ir al carrilero, a los interiores del mediocampo o al pase largo. Su inteligencia táctica es vital para el éxito del sistema.`,
        attrs: [
          { label: "Liderazgo", type: "mental" },
          { label: "Posicionamiento", type: "tactical" },
          { label: "Salida a balón largo", type: "physical" },
          { label: "Construcción", type: "technical" },
        ],
        tasks: [
          "Organizar y dirigir la línea de cinco en todas las fases del partido.",
          "Marcar al '9' rival o salir a cortar el balón cuando el equipo defiende alto.",
          "Ser la primera opción de pase del portero para iniciar la construcción.",
          "Gestionar la línea de fuera de juego coordinando a los cinco defensores.",
        ],
      },
      {
        id: "rcb",
        name: "Central Derecho",
        abbr: "DCD",
        type: "def",
        shortRole: "Defensa lateral del trío: cobertura y salida por la derecha.",
        role: `Espejo del central izquierdo, cubre al carrilero derecho cuando este sube al ataque y ejerce sus funciones defensivas en la zona derecha del área. En el sistema 5-3-2 moderno, se le exige ser buen jugador con el balón para facilitar la salida desde atrás, siendo capaz de superar las primeras líneas de pressing rival con pases al pie o pases largos cambiando el juego.`,
        attrs: [
          { label: "Cobriendo la espalda", type: "tactical" },
          { label: "Pase al carrilero", type: "technical" },
          { label: "Duelos aéreos", type: "physical" },
          { label: "1 vs 1", type: "physical" },
        ],
        tasks: [
          "Cubrir el espacio a la espalda del carrilero derecho cuando sube.",
          "Interceptar en la zona derecha del área y ganar duelos directos.",
          "Circular el balón con el central pivote y el carrilero derecho.",
          "Defender en 1v1 cuando el rival intenta aislar a su extremo en la zona.",
        ],
      },
      {
        id: "lwb",
        name: "Carrilero Izquierdo",
        abbr: "CLI",
        type: "wing",
        shortRole: "Motor de la banda izquierda: ataque y defensa constante.",
        role: `El carrilero izquierdo es uno de los jugadores más exigentes del sistema. En ataque, sube a comportarse como un lateral ofensivo o incluso un extremo, dando profundidad, centrando y combinando. En defensa, debe bajar con rapidez para retomar su posición en la línea de cinco. Necesita una condición física excepcional (resistencia, velocidad de recuperación) y alta inteligencia táctica para leer cuándo subir y cuándo permanecer.`,
        attrs: [
          { label: "Resistencia aeróbica", type: "physical" },
          { label: "Velocidad de recuperación", type: "physical" },
          { label: "Centros/centros", type: "technical" },
          { label: "Decisión táctica", type: "tactical" },
        ],
        tasks: [
          "Subir constantemente por la banda izquierda para dar amplitud ofensiva.",
          "Centrar al área o combinar con el interior o el delantero.",
          "Regresar rápidamente para completar la línea de cinco en defensa.",
          "Presionar al lateral rival cuando el bloque sube a presionar.",
        ],
      },
      {
        id: "rwb",
        name: "Carrilero Derecho",
        abbr: "CLD",
        type: "wing",
        shortRole: "Motor de la banda derecha: amplitud y trabajo intenso.",
        role: `Mismo rol que el carrilero izquierdo pero en el flanco contrario. Es el responsable de sobrecargar la banda derecha en ataque y de replegarse con diligencia para completar la línea de cinco. Su relación con el interior o mediocampista derecho y con el delantero de su lado debe estar muy bien coordinada para crear situaciones de 2v1 y generar peligro en esa banda.`,
        attrs: [
          { label: "Resistencia aeróbica", type: "physical" },
          { label: "Proyección ofensiva", type: "tactical" },
          { label: "Precisión de pase", type: "technical" },
          { label: "Duelos en banda", type: "physical" },
        ],
        tasks: [
          "Generar amplitud por la derecha en fase ofensiva.",
          "Coordinar con el interior derecho en combinaciones de una-dos.",
          "Replegarse con urgencia cuando el equipo pierde el balón.",
          "Defender individualmente al extremo/lateral rival en su banda.",
        ],
      },
      {
        id: "dm",
        name: "Mediocentro Defensivo",
        abbr: "MCD",
        type: "mid",
        shortRole: "El destructor del mediocampo: recupera y simplifica.",
        role: `En el mediocampo de tres del 5-3-2, el mediocentro defensivo es el 'destructor': quien intercepta, persigue y recupera el balón, actuando de filtro entre la defensa y los interiores. Tiene menor libertad ofensiva que sus compañeros de mediocampo, priorizando el equilibrio y la cobertura. Su lectura del juego anticipando las llegadas del rival es su mayor virtud.`,
        attrs: [
          { label: "Intercepción", type: "tactical" },
          { label: "Duelos físicos", type: "physical" },
          { label: "Cobertura defensiva", type: "tactical" },
          { label: "Pase simple", type: "technical" },
        ],
        tasks: [
          "Posicionarse entre los dos centrales y los interiores para filtrar el juego.",
          "Interceptar y recuperar el balón en los duelos del mediocampo.",
          "Apoyar a los centrales cuando la defensa es superada en zona central.",
          "Distribuir rápidamente tras recuperar para activar las transiciones.",
        ],
      },
      {
        id: "lm",
        name: "Interior Izquierdo",
        abbr: "II",
        type: "mid",
        shortRole: "Box-to-box creativo por la izquierda: gol y construcción.",
        role: `El interior izquierdo en el 5-3-2 tiene la libertad de ser el jugador más creativo o box-to-box del sistema. Avanza para apoyar a los delanteros, llega al área para rematar en segunda jugada, y en defensa cierra en el mediocampo junto al mediocentro. Su habilidad en combinaciones cortas y su llegada al área complementan el trabajo de los dos delanteros y del carrilero. Es el 'jugador total' del mediocampo.`,
        attrs: [
          { label: "Llegada", type: "tactical" },
          { label: "Calidad técnica", type: "technical" },
          { label: "Resistencia", type: "physical" },
          { label: "Visión de juego", type: "mental" },
        ],
        tasks: [
          "Asociarse con el carrilero y el delantero para crear situaciones de gol.",
          "Llegar a la segunda línea desde atrás para rematar en área.",
          "Replegarse en bloque medio para ayudar al mediocentro defensivo.",
          "Generar superioridades en el centro mediante combinaciones de pared.",
        ],
      },
      {
        id: "rm",
        name: "Interior Derecho",
        abbr: "ID",
        type: "mid",
        shortRole: "Box-to-box enérgico por la derecha: presión y llegada.",
        role: `Rol similar al interior izquierdo pero con características que pueden variar: en muchos equipos el interior derecho es algo más físico y trabajador, complementando al más creativo por la izquierda. Tiene un trabajo defensivo muy exigente: debe cerrar su banda, ayudar al carrilero en la defensa y participar activamente en las transiciones. En ataque, tiene libertad para llegar al área, buscar el disparo lejano o combinar con los delanteros.`,
        attrs: [
          { label: "Verticalidad", type: "tactical" },
          { label: "Trabajo físico", type: "physical" },
          { label: "Disparo largo", type: "technical" },
          { label: "Pressing", type: "tactical" },
        ],
        tasks: [
          "Presionar activamente al mediocentro rival en su zona.",
          "Llegar al área desde la derecha para el remate en segunda jugada.",
          "Combinar con el carrilero derecho y el delantero de referencia.",
          "Cubrir la zona cuando el carrilero derecho se proyecta al ataque.",
        ],
      },
      {
        id: "ls",
        name: "Delantero Segunda Punta",
        abbr: "SD",
        type: "att",
        shortRole: "Delantero móvil: rompedor y generador de espacios.",
        role: `En la pareja de delanteros del 5-3-2, el segundo delantero suele ser el más móvil. Puede bajar a asociarse con los interiores del mediocampo, abrir hacia la banda para liberarle espacio al 9, o encarar a los centrales rivales en diagonal. Su prioridad es desorganizar la defensa rival con movimientos inteligentes para que el delantero de referencia tenga opciones más claras de finalización.`,
        attrs: [
          { label: "Movilidad", type: "physical" },
          { label: "Desequilibrio", type: "technical" },
          { label: "Combinación", type: "technical" },
          { label: "Presión de bloque", type: "tactical" },
        ],
        tasks: [
          "Crear espacios para el 9 mediante desmarques de ruptura y apoyo.",
          "Presionar en tándem con el delantero de referencia al portero o central rival.",
          "Bajar a asociarse con los interiores para jugar entre líneas.",
          "Finalizar cuando el 9 genera el espacio o el remate no es viable para este.",
        ],
      },
      {
        id: "st",
        name: "Delantero de Referencia",
        abbr: "DR",
        type: "att",
        shortRole: "Pivot ofensivo: finalización, retención y punto de apoyo.",
        role: `El delantero de referencia en el 5-3-2 es el pivot ofensivo del equipo: retiene el balón de espaldas, gana los duelos aéreos, y finaliza con eficacia dentro del área. Cuando el equipo defiende bajo, este jugador actúa como punto de referencia para la salida directa del juego (el pase largo y la retención). Su complicidad con el segundo delantero es fundamental: ambos trabajan en dúo, presionando y combinando de forma coordinada.`,
        attrs: [
          { label: "Juego de espaldas", type: "technical" },
          { label: "Finalización", type: "technical" },
          { label: "Juego aéreo", type: "physical" },
          { label: "Asociación", type: "mental" },
        ],
        tasks: [
          "Retener el balón con el cuerpo cuando el equipo sale con balón largo.",
          "Rematar con eficacia desde todas las posiciones en el área.",
          "Ganar los duelos aéreos para ampliar el juego al carrilero o al interior.",
          "Presionar junto al segundo delantero como primera línea defensiva del equipo.",
        ],
      },
    ],
    ratings: { ataque: 72, defensa: 90, mediocampo: 74, pressing: 76, versatilidad: 68, complejidad: 72 },
    compData: {
      posesion: { label: "Posesión", value: "Media — el bloque de tres en el mediocampo no favorece el juego combinativo.", win: false },
      pressing: { label: "Pressing", value: "Organizado — pressing en bloque medio, no tan agresivo como la línea alta.", win: false },
      defensa: { label: "Solidez Defensiva", value: "Muy alta — línea de cinco sólida y tres centrales cubren todo el ancho.", win: true },
      ataque: { label: "Potencia Ofensiva", value: "Media-alta — dúo de delanteros peligroso, pero depende de los carrileros.", win: false },
      adaptacion: { label: "Adaptabilidad", value: "Media — puede ajustarse entre 3-5-2 ofensivo y 5-3-2 defensivo.", win: false },
      transiciones: { label: "Transiciones", value: "Rápidas verticales — los dos delanteros permiten salidas directas al contra.", win: false },
    },
  },
};

const RADAR_LABELS = ["Ataque", "Defensa", "Mediocampo", "Pressing", "Versatilidad", "Complejidad"];
